### PR TITLE
Fix for Showing the Mail Compose Failure Alert

### LINKED ISSUE #242: Mail Failure Alert Not Appearing
The Mail Failure alert from #237 is not appearing when attempting to send with no mail accounts.

## How to Reproduce

1. Launch the example app in a simulator with no mail accounts set up.
1. Tap "Send".

### PR DESCRIPTION
**Pull request by mliberatore**
Closes #242 

## What It Does

Fixes the issue where tapping "Send" with no mail accounts, and no other configuration specified wouldn’t display the alert.

## How to Test

1. Run the example app in a clean simulator
1. Tap "Send"

## Notes

N/A

### CODE REVIEW

File: PinpointKit/PinpointKit/Sources/Core/MailSender.swift [hunk 1]
```diff
@@ -62,13 +62,13 @@ open class MailSender: NSObject, Sender {
     open func send(_ feedback: Feedback, from viewController: UIViewController?) {
         guard let viewController = viewController else { fail(with: .noViewControllerProvided); return }
         
+        self.feedback = feedback
```
Comment (grantjbutler) [inline PinpointKit/PinpointKit/Sources/Core/MailSender.swift]: We should move this above the view controller guard, so that the `.noViewControllerProvided` error will get passed to the appropriate delegates.

File: PinpointKit/PinpointKit/Sources/Core/PinpointKit.swift [hunk 2]
```diff
@@ -59,6 +59,19 @@ open class PinpointKit {
         configuration.editor.clearAllAnnotations()
         configuration.feedbackCollector.collectFeedback(with: screenshot, from: viewController)
     }
+    
+    /// Presents an alert signifying the inability to compose a Mail message.
+    open func presentFailureToComposeMailAlert() {
+        let alert = UIAlertController(
+            title: "Can’t Send Email",
```
Comment (grantjbutler) [inline PinpointKit/PinpointKit/Sources/Core/PinpointKit.swift]: Do we need to localize these strings?

File: PinpointKit/PinpointKit/Sources/Core/MailSender.swift (hunk 1 above)
Comment (mliberatore) [reply PinpointKit/PinpointKit/Sources/Core/MailSender.swift]: Good point
