### PR TITLE
Fixes Dismiss Button Spacing

### LINKED ISSUE #224: [iOS 11] Dismiss Button Is Too Close To Segmented Control
1. Use Xcode 8 and Xcode 9 to see the differences here.
1. Run `PinpointKitExample`.
1. Tap the photo.
1. Select the text annotation.
1. Observe.

img_9470 simulator screen shot - iphone 7 - 2017-09-11 at 10 42 09

### PR DESCRIPTION
**Pull request by Twigz**
Closes #224 

## What It Does
Fixes an issue where the dismiss button was too close to the title view.

## How to Test
Test on iOS 11 and iOS 10 to make sure the dismiss/done button is appropriately spaced from the action items.

### CODE REVIEW

File: PinpointKit/PinpointKit/Sources/Core/Editing/EditImageViewController.swift [hunk 1]
```diff
@@ -408,7 +413,10 @@ open class EditImageViewController: UIViewController, UIGestureRecognizerDelegat
         let dismissButton = UIBarButtonItem(title: interfaceCustomization?.interfaceText.textEditingDismissButtonTitle, style: .done, target: self, action: #selector(EditImageViewController.endEditingTextViewIfFirstResponder))
         dismissButton.setTitleTextAttributes([NSAttributedStringKey.font: buttonFont], for: UIControlState())
         
-        navigationItem.setRightBarButton(dismissButton, animated: true)
+        let fixedSpace = UIBarButtonItem(barButtonSystemItem: .fixedSpace, target: nil, action: nil)
+        fixedSpace.width = 10
```
Comment (mliberatore) [inline PinpointKit/PinpointKit/Sources/Core/Editing/EditImageViewController.swift]: I feel that we should ensure that the width for the fixed space here matches it in its initial declaration, so could we either create a private constant in this class in a `LayoutConstants` struct, or perhaps even better, a computed property for, say, `fixedSpaceBarButtonItem` and use it in both locations?
