### PR TITLE
Hides Default Logging Capabilities on iOS 10+

### LINKED ISSUE #205: ASLLogger Not Working on Device on iOS 10 (Works in Simulator)
For more information, see: https://github.com/CocoaLumberjack/CocoaLumberjack/issues/791

To reproduce, on device:

1. Run the Example project
1. Tap the ( i ) next to "Include Console Log"
1. See that no messages are present.

Perform the same steps on a simulator to see the log from `AppDelegate.swift`.

### PR DESCRIPTION
**Pull request by mliberatore**
Closes #205.

## What it Does

See description of issue at #205, and the `- warning:` on the initializer in code. This prevents the logging section/cell from displaying on devices that can’t use ASL.

The rest of the code to support logging is in place, and if a 3rd-party logging system were used, it could be made to conform to `LogCollector` and replace `SystemLogCollector` via customization.

## How to Test

1. Run the Example project on an iOS 9.x device
1. Ensure the logging cell is there, and tapping the accessory button takes you to the log view controller with the test log present.
Ensure that logs.txt is attached to an email when sending feedback.
1. Run the Example project on an iOS 10.0 device
1. Ensure the log cell is not present at all, and no logs.txt i

### CODE REVIEW

File: PinpointKit/PinpointKit/Sources/Core/SystemLogCollector.swift [hunk 1]
```diff
@@ -22,7 +22,19 @@ open class SystemLogCollector: LogCollector {
     
     private let logger: ASLLogger
     
-    public init(loggingType: LoggingType = .application) {
+    /**
+     Creates a new system logger.
+     
+     - parameter loggingType: Specifies the type of logs to collect.
+     
+     - warning: This initializer returns `nil` on iOS 10.0+. When running on iOS 10.0+, ASL is superseded by unified logging, for which there are no APIs to search or read log messages.
```
Comment (mattbischoff) [inline PinpointKit/PinpointKit/Sources/Core/SystemLogCollector.swift]: Should we also note this in the README @mliberatore?

File: PinpointKit/PinpointKit/Sources/Core/FeedbackTableViewDataSource.swift [hunk 2]
```diff
@@ -47,15 +47,21 @@ final class FeedbackTableViewDataSource: NSObject, UITableViewDataSource {
     // MARK: - FeedbackTableViewDataSource
     
     private static func sectionsFromConfiguration(_ interfaceCustomization: InterfaceCustomization, screenshot: UIImage, logSupporting: LogSupporting, userEnabledLogCollection: Bool) -> [Section] {
-        guard logSupporting.logCollector != nil else { return [] }
+        var sections = [Section]()
```
Comment (mattbischoff) [inline PinpointKit/PinpointKit/Sources/Core/FeedbackTableViewDataSource.swift]: For some reason I prefer `var sections: [Section] = []` but that might just be me.

File: PinpointKit/PinpointKit/Sources/Core/SystemLogCollector.swift (hunk 1 above)
Comment (mliberatore) [inline PinpointKit/PinpointKit/Sources/Core/SystemLogCollector.swift]: Yeah, and we should definitely update other areas of the README in the areas where we talk about logging. I’ll do that in a separate PR if that’s okay.

File: PinpointKit/PinpointKit/Sources/Core/FeedbackTableViewDataSource.swift (hunk 2 above)
Comment (mliberatore) [inline PinpointKit/PinpointKit/Sources/Core/FeedbackTableViewDataSource.swift]: Cool with me.

File: PinpointKit/PinpointKit/Sources/Core/SystemLogCollector.swift (hunk 1 above)
Comment (mattbischoff) [inline PinpointKit/PinpointKit/Sources/Core/SystemLogCollector.swift]: That’s fine.
