### PR TITLE
[Swift 2.3] Fixes Gap on FeedbackViewController

### LINKED ISSUE #128: (iOS 10) Large Gap on Feedback View
On iOS 10, there’s a lot of space between components:
simulator screen shot jun 24 2016 3 18 02 pm

### PR DESCRIPTION
**Pull request by mliberatore**
Closes #128

See #160 for all details of when this was completed for Swift 3. This is simply a Swift 2.3 port.

### CODE REVIEW

**Comment by freak4pc** [comment]
Anyone who can review this so we can get that fixed in 2.3 ?

**Comment by mattbischoff** [comment]
@Twigz Can you give this a look today?

File: PinpointKit/PinpointKit/Sources/FeedbackTableViewDataSource.swift [hunk 1]
```diff
@@ -36,18 +40,56 @@ final class FeedbackTableViewDataSource: NSObject, UITableViewDataSource {
     }
     
     private enum Row {
+        case Screenshot(screensot: UIImage, hintText: String?, hintFont: UIFont)
```
Comment (Twigz) [inline PinpointKit/PinpointKit/Sources/FeedbackTableViewDataSource.swift]: It seems strange that the hint text is optional, but the hintFont is not?

File: PinpointKit/PinpointKit/Sources/ScreenshotCell.swift [hunk 2]
```diff
@@ -100,9 +101,22 @@ class ScreenshotHeaderView: UIView {
         screenshotButton.layer.borderColor = tintColor.CGColor
     }
     
-    // MARK: - ScreenshotHeaderView
+    override func addSubview(_ view: UIView) {
+        // Prevents the adding of separators to this cell.
+        let separatorHeight = 1.0 / UIScreen.mainScreen().scale
```
Comment (Twigz) [inline PinpointKit/PinpointKit/Sources/ScreenshotCell.swift]: I think it would be nice to have this be an extension on `UIScreen`. Something like `pixelHeight`.

File: PinpointKit/PinpointKit/Sources/FeedbackTableViewDataSource.swift (hunk 1 above)
Comment (mliberatore) [inline PinpointKit/PinpointKit/Sources/FeedbackTableViewDataSource.swift]: I believe this merely reflects the optionality of `InterfaceCustomization.Appearance.feedbackEditHintFont` and `InterfaceCustomization.Appearance.feedbackEditHint`. Really it is that we never won’t have a `hintFont` since it has a default value on initialization of `InterfaceCustomization`. How would you like to proceed? I can make `hintFont` optional here, but it will have no effect.
